import React from 'react';
import type { Metadata } from "next";
import StyledComponentsRegistry from '../lib/StyledComponentsRegistry';
import { Geist, Geist_Mono } from "next/font/google";
import 'bootswatch/dist/sandstone/bootstrap.min.css';
import ReactQueryProviders from '../utils/react-query-provider';
import Loading from './loading';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProviders>
          <StyledComponentsRegistry>
            <Loading />
            {children}
          </StyledComponentsRegistry>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
